// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzFWeI3qmD8ouYn7dalkypX4aIX9o2vIc',
    appId: '1:620394483026:web:f1dc374b2ae8fb81e6be8b',
    messagingSenderId: '620394483026',
    projectId: 'hksa-3f5d4',
    authDomain: 'hksa-3f5d4.firebaseapp.com',
    databaseURL: 'https://hksa-3f5d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hksa-3f5d4.appspot.com',
    measurementId: 'G-DFF2118YN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy8UZ0yDidA7nTW8H70ibuk_Ow9WPt47A',
    appId: '1:620394483026:android:1604b14b5abdad9ae6be8b',
    messagingSenderId: '620394483026',
    projectId: 'hksa-3f5d4',
    databaseURL: 'https://hksa-3f5d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hksa-3f5d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35S-O4gFwffTpyL2VpXi7td1neR82W-I',
    appId: '1:620394483026:ios:dff5760108c08ce6e6be8b',
    messagingSenderId: '620394483026',
    projectId: 'hksa-3f5d4',
    databaseURL: 'https://hksa-3f5d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hksa-3f5d4.appspot.com',
    iosClientId: '620394483026-rjfqqkjsakfr9n1c2hmbm717ml15j269.apps.googleusercontent.com',
    iosBundleId: 'com.example.hksa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB35S-O4gFwffTpyL2VpXi7td1neR82W-I',
    appId: '1:620394483026:ios:dff5760108c08ce6e6be8b',
    messagingSenderId: '620394483026',
    projectId: 'hksa-3f5d4',
    databaseURL: 'https://hksa-3f5d4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hksa-3f5d4.appspot.com',
    iosClientId: '620394483026-rjfqqkjsakfr9n1c2hmbm717ml15j269.apps.googleusercontent.com',
    iosBundleId: 'com.example.hksa',
  );
}
